patient/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.patient_index, name='index'),
    url(r'^(\d+)/$', views.patient_show),
    url(r'^get$', views.patient_get),
    url(r'^create$', views.patient_create),
    url(r'^(\d+)/appointment/create$', views.appointment_create),
    url(r'^(\d+)/appointment/(\d+)$', views.appointment_show),
    url(r'^appointment/get$', views.appointment_get),
    url(r'^lab_result/create$', views.lab_result_create),
    url(r'^lab_result/store$', views.lab_result_store),
    url(r'^(\d+)/lab_result/(\d+)$', views.lab_result_show),
    url(r'^(\d+)/visit/create$', views.visit_create),
    url(r'^(\d+)/vitals/create$', views.vitals_create),
    url(r'^(\d+)/vitals/trend/(\w+)$', views.vitals_trend),
    url(r'^(\d+)/screening/create$', views.screening_create),
    url(r'^(\d+)/screening/(\d+)$', views.screening_show),
    url(r'^(\d+)/treatment/create$', views.treatment_create),
    url(r'^treatment/get$', views.treatment_get),
]

tbdc/urls.py
from django.conf import settings
from django.conf.urls import include, url, patterns
from django.contrib import admin
import patient.views

# admin.autodiscover()

urlpatterns = [
    url(r'^$', patient.views.index),
    url(r'^prevalence/', patient.views.prevalence),
    url(r'^patient/', include('patient.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}))

patient/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
import random, string

# Create your models here.
class Patient(models.Model):
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
    )
    identifier = models.CharField(max_length=255)
    first_name = models.CharField(max_length=127)
    last_name = models.CharField(max_length=127)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, default='M')
    birthdate = models.DateField()
    address = models.CharField(max_length=255)
    address2 = models.CharField(max_length=255, null=True)
    city = models.CharField(max_length=63)
    province = models.CharField(max_length=63)
    country = models.CharField(max_length=63)
    phone_number = models.CharField(max_length=63)
    date_created = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.PROTECT)

class Visit(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    diagnoses = models.CharField(max_length=255)
    notes = models.TextField()
    creator = models.ForeignKey(User)
    date_created = models.DateTimeField(auto_now_add=True)

class Vitals(models.Model):
    height = models.DecimalField(max_digits=5, decimal_places=2)
    weight = models.DecimalField(max_digits=5, decimal_places=2)
    temperature = models.IntegerField()
    pulse = models.IntegerField()
    respiratory_rate = models.IntegerField()
    bp_systole = models.IntegerField()
    bp_diastole = models.IntegerField()
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    creator = models.ForeignKey(User)
    date_created = models.DateTimeField(auto_now_add=True)

class LabResult(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    test_name = models.CharField(max_length=127)
    img = models.CharField(max_length=255)
    result = models.CharField(max_length=127)
    creator = models.ForeignKey(User)
    date_created = models.DateTimeField(auto_now_add=True)

class Treatment(models.Model):
    DRUG_CHOICES = (
        ('HRZE', 'FDC 4 combination (HRZE)'),
        ('HR', 'FDC 2 combination (HR)'),
        ('H', 'Isoniazid (H)'),
        ('R', 'Rifampisin (R)'),
        ('Z', 'Pirazinamid (Z)'),
        ('E', 'Etambutol (E)'),
        ('S', 'Streptomisin (S)'),
        ('HRZ', 'FDC for children (HRZ)'),
        ('Km', 'Kanamysin (Km)'),
        ('Cm', 'Capreomysin (Cm)'),
        ('Lfx', 'Levofloksasin (Lfx)'),
        ('Mfx', 'Moksifloksasin (Mfx)'),
        ('Etio', 'Ethionamide (Etio)'),
        ('Cs', 'Cycloserine (Cs)'),
        ('PAS', 'Para-aminosalicyclic Acid (PAS)'),
    )
    medication = models.CharField(max_length=7, choices=DRUG_CHOICES)
    dosage = models.DecimalField(max_digits=15, decimal_places=2)
    freq_day = models.IntegerField()
    freq_week = models.IntegerField()
    start_date = models.DateField()
    end_date = models.DateField()
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    creator = models.ForeignKey(User)
    date_created = models.DateTimeField(auto_now_add=True)

class Appointment(models.Model):
    SERVICE_CHOICES = (
        ('C', 'Consultation'),
        ('L', 'Lab test'),
        ('M', 'Medical check up'),
    )
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    service_type = models.CharField(max_length=255, choices=SERVICE_CHOICES)
    agenda = models.TextField()
    date = models.DateTimeField()
    creator = models.ForeignKey(User)
    date_created = models.DateTimeField(auto_now_add=True)

class Screening(models.Model):
    HIV_CHOICES = (
        ('1', 'Yes'),
        ('0', 'No'),
        ('99', 'Unknown'),
    )
    TB_EXPOSURE_CHOICES = (
        ('1', 'One member of family in the same house had previous TB'),
        ('2', 'One member of family in the same house has active TB infection'),
        ('3', 'Contact with person infected with TB'),
        ('99', 'Unknown'),
    )
    DIAGNOSIS_CHOICES = (
        ('1', 'Suspect TB'),
        ('2', 'Confirm Positive TB'),
        ('0', 'Negative TB'),
    )
    TB_PATIENT_STATUS_CHOICES = (
        ('1', 'New'),
        ('2', 'Chronic'),
        ('3', 'Relapse'),
        ('4', 'Drop out'),
        ('99', 'NA'),
    )
    cough = models.BooleanField()
    haemoptysis = models.BooleanField()
    chest_pain = models.BooleanField()
    weight_loss = models.BooleanField()
    fatigue = models.BooleanField()
    fever = models.BooleanField()
    night_sweats = models.BooleanField()
    chills = models.BooleanField()
    other_symptoms = models.BooleanField()
    diagnosis = models.CharField(max_length=7, choices=DIAGNOSIS_CHOICES)
    tb_patient_status = models.CharField(max_length=7, choices=TB_PATIENT_STATUS_CHOICES, default=0)
    meningitis = models.BooleanField()
    pregnant = models.BooleanField()
    immunocompromised = models.BooleanField()
    malnutrition = models.BooleanField()
    coinfection = models.BooleanField()
    comorbid = models.BooleanField()
    hiv = models.CharField(max_length=15, choices=HIV_CHOICES)
    tb_exposure = models.CharField(max_length=7, choices=TB_EXPOSURE_CHOICES)
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    creator = models.ForeignKey(User, default=1)
    date_created = models.DateTimeField(auto_now_add=True)

patient/views.py
from wsgiref.util import FileWrapper
from django.core.serializers.json import DjangoJSONEncoder
from django.core.urlresolvers import reverse
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.views.decorators.csrf import csrf_protect, csrf_exempt
from patient.models import *
from patient.quinn import detect_mtb
from shutil import move
from datetime import datetime, date
from twilio.rest import TwilioRestClient
import json
import logging
import subprocess
import os

logger = logging.getLogger(__name__)

def generateID():
    return ''.join(random.sample(set(string.letters.upper()), 3) + random.sample(string.digits, 5))

def calculate_age(born):
    today = date.today()
    return today.year - born.year - ((today.month, today.day) < (born.month, born.day))

# Create your views here.
@login_required
def index(request):
    return render(request, 'index.html')

def patient_get(request):
    response_data = {}
    if request.method == 'GET':
        if not request.GET.get('query', ''):
            response_data['status'] = 'success'
            response_data['message'] = Patient.objects.all()
        else:
            query = request.GET['query']
            data = Patient.objects.filter(
                Q(first_name__icontains=query) | Q(last_name__icontains=query) | Q(identifier__icontains=query)
            )
            response_data['status'] = 'success'
            response_data['message'] = list(data.values())

        return HttpResponse(json.dumps(response_data, cls=DjangoJSONEncoder), content_type='application/json')
    response_data['status'] = 'error'
    response_data['message'] = 'Method not allowed!'
    return HttpResponse(json.dumps(response_data), content_type='application/json')

@login_required
def patient_index(request):
    return render(request, 'patient/index.html', {'query': request.GET.get('query', '')})

@login_required
def patient_create(request):
    if request.method == 'POST':
        fields = ['first_name', 'last_name', 'birthdate', 'address', 'city', 'province', 'country', 'phone_number']
        empty_field = []
        for field in fields:
            if not request.POST.get(field, ''):
                empty_field.append(field)
        if empty_field:
            messages.error(request, 'Please fill out these fields: %s' % ', '.join(empty_field))
        else:
            identifier = generateID()
            user = User.objects.create_user(identifier, password=identifier,
                first_name=request.POST['first_name'], last_name=request.POST['last_name'])
            patient = user.patient_set.create(
                identifier=identifier,
                first_name=request.POST['first_name'],
                last_name=request.POST['last_name'],
                birthdate=request.POST['birthdate'],
                address=request.POST['address'],
                city=request.POST['city'],
                province=request.POST['province'],
                country=request.POST['country'],
                phone_number=request.POST['phone_number']
            )
            patient.save()
            return HttpResponseRedirect(reverse('patient.views.patient_show', args=(patient.id,)))
    data = {}
    name = request.GET.get('name', '').split(' ')
    if name:
        data['first_name'] = ' '.join(name[:-1])
        data['last_name'] = name[-1]
    data['birthdate'] = request.GET.get('birthdate', '')
    data['gender'] = request.GET.get('gender', '')
    return render(request, 'patient/create.html', {'data': data})

@login_required
def patient_show(request, patient_id):
    patient = Patient.objects.get(id=patient_id)
    patient.age = calculate_age(patient.birthdate)
    visits = patient.visit_set.order_by('-date_created')
    if visits:
        last_visit = visits[0]
    else:
        last_visit = None
    vitals = patient.vitals_set.order_by('-date_created')
    if vitals:
        vitals = vitals[0]
    upcoming = patient.appointment_set.filter(date__gte=date.today()).order_by('date')
    if upcoming:
        upcoming = upcoming[0]
    data = {
        'patient': patient,
        'screenings': patient.screening_set.all(),
        'lab_results': patient.labresult_set.order_by('-date_created').all(),
        'treatments': patient.treatment_set.all(),
        'appointments': patient.appointment_set.filter(date__lt=date.today()),
        'visits': visits,
        'last_visit': last_visit,
        'vitals': vitals,
        'upcoming_appt': upcoming
    }
    return render(request, 'patient/show.html', data)

def screening_create(request, patient_id):
    if request.method == 'POST':
        fields = [
            'diagnosis',
            'hiv',
            'tb_exposure'
        ]
        empty_field = []
        for field in fields:
            if not request.POST.get(field, ''):
                empty_field.append(field)
        if empty_field:
            messages.error(request, 'Please fill out these fields: %s' % ', '.join(empty_field))
        else:
            user = User.objects.get(id=1)
            patient = Patient.objects.get(id=patient_id)
            screening = patient.screening_set.create(
                cough = request.POST.get('cough', False),
                haemoptysis = request.POST.get('haemoptysis', False),
                chest_pain = request.POST.get('chest_pain', False),
                weight_loss = request.POST.get('weight_loss', False),
                fatigue = request.POST.get('fatigue', False),
                fever = request.POST.get('fever', False),
                night_sweats = request.POST.get('night_sweats', False),
                chills = request.POST.get('chills', False),
                other_symptoms = request.POST.get('other_symptoms', False),
                diagnosis = request.POST.get('diagnosis', ''),
                tb_patient_status = request.POST.get('tb_patient_status', 0),
                meningitis = request.POST.get('meningitis', False),
                pregnant = request.POST.get('pregnant', False),
                immunocompromised = request.POST.get('immunocompromised', False),
                malnutrition = request.POST.get('malnutrition', False),
                coinfection = request.POST.get('coinfection', False),
                comorbid = request.POST.get('comorbid', False),
                hiv = request.POST['hiv'],
                tb_exposure = request.POST['tb_exposure'],
                creator = user
            )
            messages.success(request, 'TB screening form recorded.')
            return HttpResponseRedirect(reverse('patient.views.patient_show', args=(patient.id,)))
    patient = Patient.objects.get(id=patient_id)
    patient.age = calculate_age(patient.birthdate)
    return render(request, 'screening/create.html', {'patient': patient})

def screening_show(request, patient_id, screening_id):
    patient = Patient.objects.get(id=patient_id)
    patient.age = calculate_age(patient.birthdate)
    screening = Screening.objects.get(id=screening_id)
    return render(request, 'screening/show.html', {'patient': patient, 'screening': screening})

def visit_create(request, patient_id):
    if request.method == 'POST':
        fields = ['diagnoses', 'notes']
        empty_field = []
        for field in fields:
            if not request.POST.get(field, ''):
                empty_field.append(field)
        if empty_field:
            messages.error(request, 'Please fill out these fields: %s' % ', '.join(empty_field))
        else:
            user = User.objects.get(id=1)
            patient = Patient.objects.get(id=patient_id)
            visit = patient.visit_set.create(
                diagnoses=request.POST['diagnoses'],
                notes=request.POST['notes'],
                creator=user
            )
            messages.success(request, 'Visit notes recorded.')
            return HttpResponseRedirect(reverse('patient.views.patient_show', args=(patient.id,)))
    patient = Patient.objects.get(id=patient_id)
    patient.age = calculate_age(patient.birthdate)
    return render(request, 'visit/create.html', {'patient': patient})

def vitals_create(request, patient_id):
    if request.method == 'POST':
        fields = ['height', 'weight', 'temperature', 'pulse', 'respiratory_rate', 'bp_systole', 'bp_diastole']
        empty_field = []
        for field in fields:
            if not request.POST.get(field, ''):
                empty_field.append(field)
        if empty_field:
            messages.error(request, 'Please fill out these fields: %s' % ', '.join(empty_field))
        else:
            user = User.objects.get(id=1)
            patient = Patient.objects.get(id=patient_id)
            vitals = patient.vitals_set.create(
                height=request.POST['height'],
                weight=request.POST['weight'],
                temperature=request.POST['temperature'],
                pulse=request.POST['pulse'],
                respiratory_rate=request.POST['respiratory_rate'],
                bp_systole=request.POST['bp_systole'],
                bp_diastole=request.POST['bp_diastole'],
                creator=user
            )
            messages.success(request, 'Vitals recorded.')
            return HttpResponseRedirect(reverse('patient.views.patient_show', args=(patient.id,)))
    patient = Patient.objects.get(id=patient_id)
    patient.age = calculate_age(patient.birthdate)
    return render(request, 'vitals/create.html', {'patient': patient})

def vitals_trend(request, patient_id, column):
    patient = Patient.objects.get(id=patient_id)
    patient.age = calculate_age(patient.birthdate)
    vitals = patient.vitals_set.order_by('date_created')
    labels = '"%s"' % ','.join([v.date_created.strftime('%Y-%m-%d') for v in vitals])

patient/templates/patient/create.html
{% extends 'index.html' %}
{% load staticfiles %}

{% block content %}
<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
    <h1 class="page-header">Enroll New Patient</h1>
    {% if messages %}
    <div class="alert alert-danger">
        {% for message in messages %}
        <i class="fa fa-exclamation-triangle"></i> <strong>Oops!</strong> {{ message }}
        {% endfor %}
    </div>
  {% endif %}
    <form action="" method="post">
        {% csrf_token %}
        <legend>Demographics</legend>
        <div class="form-group">
          <label for="first_name">Given Name</label>
          <input type="text" id="first_name" name="first_name" placeholder="" required="true" value="{{ data.first_name }}" class="form-control">
        </div>
        <div class="form-group">
          <label for="last_name">Family Name</label>
          <input type="text" id="last_name" name="last_name" placeholder="" required="true" value="{{ data.last_name }}" class="form-control">
        </div>
        <div class="form-group">
          <label for="birthdate">Birthdate</label>
          <input type="text" id="birthdate" name="birthdate" placeholder="YYYY-MM-DD" required="true" value="{{ data.birthdate }}" class="form-control">
        </div>
        <div class="form-group">
          <label for="gender">Gender</label><br>
          <label class="radio-inline">
            <input type="radio" name="gender" id="inlineRadio1" value="M" {% if data.gender == 'M' %}checked{% endif %}>Male
          </label>
          <label class="radio-inline">
            <input type="radio" name="gender" id="inlineRadio2" value="F" {% if data.gender == 'F' %}checked{% endif %}>Female
          </label>
        </div>
        <legend>Contact Info</legend>
        <div class="form-group">
          <label for="address">Address</label>
          <input type="text" id="address" name="address" placeholder="" class="form-control">
        </div>
        <div class="form-group">
          <label for="address2">Address 2</label>
          <input type="text" id="address2" name="address2" placeholder="" class="form-control">
        </div>
        <div class="form-group">
          <label for="city">City/Village</label>
          <input type="text" id="city" name="city" placeholder="" class="form-control">
        </div>
        <div class="form-group">
          <label for="province">State/Province</label>
          <input type="text" id="province" name="province" placeholder="" class="form-control">
        </div>
        <div class="form-group">
          <label for="country">Country</label>
          <input type="text" id="country" name="country" placeholder="" class="form-control">
        </div>
        <div class="form-group">
          <label for="phone_number">Phone Number</label>
          <input type="phone" id="phone_number" name="phone_number" placeholder="" class="form-control">
        </div>
        <button type="submit" class="btn btn-primary">Submit</button><a href="{% url 'index' %}" class="btn btn-default">Cancel</a>
    </form>
</div>
{% endblock %}

{% block javascript %}
{% endblock %}

patient/templates/patient/index.html
{% extends 'index.html' %}
{% load staticfiles %}

{% block content %}
<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
    <h1 class="page-header">Find Patient Record</h1>
    <div id="patient-list"></div>
</div>
{% endblock %}

{% block javascript %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/react/0.14.7/react.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/react/0.14.7/react-dom.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/babel-core/5.8.23/browser.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.5/marked.min.js"></script>
<script type="text/babel">
var FilteredList = React.createClass({
  filterList: function(event){
    var updatedList = this.state.initialPatients;
    updatedList = updatedList.filter(function(patient){
      return patient.identifier.toLowerCase().search(
        event.target.value.toLowerCase()) !== -1;
    });
    this.setState({patients: updatedList});
  },
  getInitialState: function(){
    return {initialPatients: [], patients: []};
  },
  componentDidMount: function(){
    $.ajax({
      url: this.props.url + '?query=' + this.props.query,
      dataType: 'json',
      cache: false,
      success: function(data) {
        console.log(data);
        this.setState({initialPatients: data.message, patients: data.message});
      }.bind(this),
      error: function(xhr, status, err) {
        console.error(this.props.url, status, err.toString());
      }.bind(this)
    });
  },
  handleSubmit: function(e) {
    
  },
  render: function(){
    return (
      <div>
        <form onSubmit={this.handleSubmit}>
          <div className="form-group">
            <label htmlFor="query">Find patient(s)</label>
            <input name="query" type="text" className="form-control" id="query" placeholder="Search by ID or name" onChange={this.filterList} />
          </div>
        </form>
        <table className="table table-hover">
          <thead>
            <tr>
              <th>Identifier</th>
              <th>Name</th>
              <th>Gender</th>
              <th>Birthdate</th>
            </tr>
          </thead>
          <List patients={this.state.patients}/>
        </table>
      </div>
    );
  }
});

var List = React.createClass({
  render: function() {
    var patients = this.props.patients.map(function(patient) {
      var xhref = "/patient/" + patient.id;
      return (<tr key={patient.identifier}>
        <td><a href={xhref}>{patient.identifier}</a></td>
        <td>{patient.first_name} {patient.last_name}</td>
        <td>{patient.gender}</td>
        <td>{patient.birthdate}</td>
      </tr>);
    });
    return (<tbody>
        {patients}
      </tbody>
    );
  }
});
ReactDOM.render(<FilteredList url="{% url 'patient.views.patient_get' %}" query="{{ query }}"/>, document.getElementById('patient-list'));
</script>
{% endblock %}

patient/templates/patient/show.html
{% extends 'index.html' %}
{% load staticfiles %}

{% block content %}
<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
  {% block pageheader %}
  <h1 class="page-header">Patient Dashboard</h1>
  {% endblock %}
  <h2><a href="{% url 'patient.views.patient_show' patient.id %}">{{ patient.first_name }} {{ patient.last_name }}</a><span class="pull-right">Patient ID: {{ patient.identifier }}</span></h2>
  <p>{{ patient.gender }}, {{ patient.age }} yo - {{ patient.birthdate }}</p>
  <hr>
  {% block body %}
  {% if messages %}
    <div class="alert alert-success">
        {% for message in messages %}
        <i class="fa fa-check"></i> <strong>Success!</strong> {{ message }}
        {% endfor %}
    </div>
  {% endif %}
  <div class="row">
    <div class="col-md-5">
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h3 class="panel-title"><i class="fa fa-stethoscope"></i> Diagnoses</h3>
        </div>
        <div class="panel-body"><strong>Last updated: {{ last_visit.date_created }}</strong></div>
        <ul class="list-group">
          {% for visit in visits %}
          <li class="list-group-item">{{ visit.diagnoses }}</li>
          {% endfor %}
        </ul>
      </div>
      <div class="panel panel-success">
        <div class="panel-heading">
          <h3 class="panel-title"><i class="fa fa-heartbeat"></i> Vitals</h3>
        </div>
        <div class="panel-body"><strong>Last updated: {{ vitals.date_created }}</strong></div>
        <ul class="list-group">
          <li class="list-group-item"><a href="{% url 'patient.views.vitals_trend' patient.id 'height' %}" class="text-success">Height</a><span class="pull-right">{{ vitals.height }} cm</span></li>
          <li class="list-group-item"><a href="{% url 'patient.views.vitals_trend' patient.id 'weight' %}" class="text-success">Weight</a><span class="pull-right">{{ vitals.weight }} kg</span></li>
          <li class="list-group-item"><a href="{% url 'patient.views.vitals_trend' patient.id 'temperature' %}" class="text-success">Temperature</a><span class="pull-right">{{ vitals.temperature }}°C</span></li>
          <li class="list-group-item"><a href="{% url 'patient.views.vitals_trend' patient.id 'pulse' %}" class="text-success">Pulse</a><span class="pull-right">{{ vitals.pulse }}/min</span></li>
          <li class="list-group-item"><a href="{% url 'patient.views.vitals_trend' patient.id 'respiratory_rate' %}" class="text-success">Respiratory rate</a><span class="pull-right">{{ vitals.respiratory_rate }}/min</span></li>
          <li class="list-group-item"><a href="#" class="text-success">Blood pressure</a><span class="pull-right">{{ vitals.bp_systole }}/{{ vitals.bp_diastole }}</span></li>
        </ul>
      </div>
      <div class="panel panel-warning">
        <div class="panel-heading">
          <h3 class="panel-title"><i class="fa fa-file-text"></i> Lab Result</h3>
        </div>
        <table class="table">
          <thead>
            <tr>
              <th>Test</th>
              <th>Result</th>
              <th>Date</th>
            </tr>
          </thead>
          <tbody>
            {% for lab_result in lab_results %}
            <tr>
              <td><a href="{% url 'patient.views.lab_result_show' patient.id lab_result.id %}">{{ lab_result.test_name }}</a></td>
              <td>{{ lab_result.result }}</td>
              <td>{{ lab_result.date_created }}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
    <div class="col-md-5">
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h3 class="panel-title"><span aria-hidden="true" class="glyphicon glyphicon-calendar"></span> Appointments</h3>
        </div>
        <div class="panel-body"><strong>Upcoming appointment: {{ upcoming_appt.date }}</strong></div>
        <div class="list-group">
            {% for appointment in appointments %}
            <a href="{% url 'patient.views.appointment_show' patient.id appointment.id %}" class="list-group-item">{{ appointment.date }}</a>
            {% endfor %}
        </div>
      </div>
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h3 class="panel-title"><i class="fa fa-medkit"></i> Treatment</h3>
        </div>
        <table class="table">
          <thead>
            <tr>
              <th>Item</th>
              <th>Dose</th>
              <th>Frequency</th>
              <th>Start date</th>
            </tr>
          </thead>
          <tbody>
            {% for treatment in treatments %}
            <tr>
              <td>{{ treatment.get_medication_display }}</td>
              <td>{{ treatment.dosage }} mg</td>
              <td>{{ treatment.freq_day }}/day | {{ treatment.freq_week }}/week</td>
              <td>{{ treatment.start_date }}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
      <div class="panel panel-info">
        <div class="panel-heading">
          <h3 class="panel-title"><span aria-hidden="true" class="glyphicon glyphicon-pencil"></span> Notes</h3>
        </div>
        <div class="panel-body">
          {% for screening in screenings %}
          <div class="col-sm-12"><a href="{% url 'patient.views.screening_show' screening.patient.id screening.id %}">Screening form - {{ screening.date_created }}</a></div>
          {% endfor %}
          <div class="col-sm-12">{{ last_visit.notes }}</div>
        </div>
      </div>
    </div>
    <div class="col-md-2">
      <legend>Current Visit Actions</legend>
      <ul>
        <li><a href="#">End Visit</a></li>
        <li><a href="{% url 'patient.views.screening_create' patient.id %}">TB Form</a></li>
        <li><a href="{% url 'patient.views.visit_create' patient.id %}">Visit Notes</a></li>
        <li><a href="{% url 'patient.views.vitals_create' patient.id %}">Capture Vitals</a></li>
        <li><a href="{% url 'patient.views.treatment_create' patient.id %}">Treatment</a></li>
      </ul>
      <legend>General Actions</legend>
      <ul>
        <li><a href="{% url 'patient.views.appointment_create' patient.id %}">Schedule Appointment</a></li>
      </ul>
    </div>
  </div>
  {% endblock %}
</div>
{% endblock %}